import 'package:super_rugby_fantasy/domain/core/value_objects.dart';
import 'package:super_rugby_fantasy/domain/team/player.dart';

List<Player> playersData = [
  Player(
      id: UniqueId(),
      selected: true,
      name: "Morne Steyn",
      originalTeam: "Chiefs",
      position: "FB",
      isCaptain: true,
      hasRedCard: false,
      hasYellowCard: false,
      points: 12,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Daniel Carter",
      originalTeam: "Chiefs",
      position: "WG",
      isCaptain: false,
      hasRedCard: true,
      hasYellowCard: false,
      points: 20,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Johnny Wilkinson",
      originalTeam: "Chiefs",
      position: "WG",
      isCaptain: false,
      hasRedCard: true,
      hasYellowCard: false,
      points: 6,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Jason Robinson",
      originalTeam: "Chiefs",
      position: "CT",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: false,
      points: 8,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Elton Jantjies",
      originalTeam: "Chiefs",
      position: "CT",
      isCaptain: false,
      hasRedCard: true,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Aaron Cruden",
      originalTeam: "Chiefs",
      position: "FH",
      isCaptain: false,
      hasRedCard: true,
      hasYellowCard: false,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Palyer 9",
      originalTeam: "Chiefs",
      position: "SH",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Palyer 8",
      originalTeam: "Chiefs",
      position: "8TH",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Palyer 7",
      originalTeam: "Chiefs",
      position: "FL",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Palyer 6",
      originalTeam: "Chiefs",
      position: "FL",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Palyer 5",
      originalTeam: "Chiefs",
      position: "SR",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Palyer 4",
      originalTeam: "Chiefs",
      position: "SR",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Player 3",
      originalTeam: "Chiefs",
      position: "HK",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Player 2",
      originalTeam: "Chiefs",
      position: "PR",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: true,
      name: "Player 1",
      originalTeam: "Chiefs",
      position: "PR",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: false,
      name: "Player 16",
      originalTeam: "Chiefs",
      position: "PR",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: false,
      name: "Player 17",
      originalTeam: "Chiefs",
      position: "PR",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  Player(
      id: UniqueId(),
      selected: false,
      name: "Player 18",
      originalTeam: "Chiefs",
      position: "FL",
      isCaptain: false,
      hasRedCard: false,
      hasYellowCard: true,
      points: 19,
      tries: 2,
      penalties: 0,
      conversions: 3,
      dropGoals: 1,
      profileImage: "",
      price: 10000),
  // Player(
  //     id: UniqueId(),
  //     selected: false,
  //     name: "Player 19",
  //     originalTeam: "Chiefs",
  //     position: "WG",
  //     isCaptain: false,
  //     hasRedCard: false,
  //     hasYellowCard: true,
  //     points: 19,
  //     tries: 2,
  //     penalties: 0,
  //     conversions: 3,
  //     dropGoals: 1,
  //     profileImage: "",
  //     price: 10000),
];
